kind: Namespace
apiVersion: v1
metadata:
  name: peira

---

apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkR2xuWlhKaEsyUmxiVzlmY0dWcGNtRTZUVFJXTVRaU1QxTkdWMHN5UkUxWFRGUkpSREJYVFV0S01FdEZURUphVDA1VE9WRkRRakJFVjFSVlFUWTJSemhEU0RrNFRVc3lSRXhXVTBveU5GZEVXQT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
kind: Secret
metadata:
  namespace: peira
  name: tigera-pull-secret
type: kubernetes.io/dockerconfigjson

---

kind: Service
apiVersion: v1
metadata:
  name: peira-operator
  namespace: peira
spec:
  selector:
    app: peira
    component: operator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: operator

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: peira-operator
  namespace: peira
  labels:
    app: peira
    component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peira
      component: operator
  template:
    metadata:
      labels:
        app: peira
        component: operator
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: operator
        image: quay.io/tigera/peira:v0.1.16_pre-k8s-1.9
        args:
        - "operator"
        - "--mockServiceAccount"
        - "peira-mock"
        - "--serviceName"
        - "peira-operator"
        - "--servicePort"
        - "8080"
        - "--pullSecretName"
        - "tigera-pull-secret"
        ports:
        - name: operator
          containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: peira-ui
  namespace: peira
spec:
  type: NodePort
  selector:
    app: peira
    component: ui
  ports:
  - name: ui
    protocol: TCP
    port: 8080
    nodePort: 33002
    targetPort: ui

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: peira-ui
  namespace: peira
  labels:
    app: peira
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peira
      component: ui
  template:
    metadata:
      labels:
        app: peira
        component: ui
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: operator
        image: quay.io/tigera/peira:v0.1.16_pre-k8s-1.9
        args:
        - "ui"
        - "--listenPort"
        - "8080"
        ports:
        - name: ui
          containerPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: peira
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: peira
  name: mockservice-egress
spec:
  podSelector:
    matchLabels:
      peira: "true"
  policyTypes:
  - Egress
  egress:
  - {}
  

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: peira
  name: mock-allow-proberesult
spec:
  podSelector:
    matchLabels:
      peira: "true"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: peira
          component: operator
    ports:
    - protocol: TCP
      port: 9000

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: peira
  name: operator-allow-api
spec:
  podSelector:
    matchLabels:
      app: peira
      component: operator
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          peira: "true"
    ports:
    - protocol: TCP
      port: 8080

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: peira
  name: mockservice-egress
spec:
  podSelector:
    matchLabels:
      app: peira
      component: ui
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080