apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkR2xuWlhKaEsyUmxiVzlmY0dWcGNtRTZUVFJXTVRaU1QxTkdWMHN5UkUxWFRGUkpSREJYVFV0S01FdEZURUphVDA1VE9WRkRRakJFVjFSVlFUWTJSemhEU0RrNFRVc3lSRXhXVTBveU5GZEVXQT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
kind: Secret
metadata:
  namespace: peira
  name: tigera-pull-secret
type: kubernetes.io/dockerconfigjson
